java banks.ThreadScheduler 20 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 30 false false >> testRuns\data.txt
