java banks.ThreadScheduler 20 20 false false > testRuns\data.txt
java banks.ThreadScheduler 20 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 20 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 25 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 30 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 35 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 20 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 25 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 30 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 35 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 40 false false >> testRuns\data.txt
java banks.ThreadScheduler 40 40 false false >> testRuns\data.txt
